name: Build Automation with GitHub actions

on:
  push:
    branches:
      - main
      - feature/ImplementazioneBadge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Code Coverage with JaCoCo and Build with Maven
      run: |
        mkdir -p Report
        cd roman-number
        mvn clean verify jacoco:report checkstyle:checkstyle | tee ../Report/build.log

    - name: Write build report on README.md
      run: |
        if [ ! -f README.md ]; then
          echo "# Build & Coverage Report" > README.md
        fi
        echo "## Build Log (last 25 rows):" >> README.md
        echo '' >> README.md
        tail -n 25 Report/build.log >> README.md
        echo "" >> README.md
        echo "## CSV of Jacoco Code Coverage:" >> README.md
        echo '```csv' >> README.md
        head -n 1 roman-number/target/site/jacoco/jacoco.csv >> README.md
        tail -n +2 roman-number/target/site/jacoco/jacoco.csv >> README.md
        echo '```' >> README.md

    - name: Commit the README.md
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md
        git commit -m "README.md updated with Build log"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: roman-number/target/site/jacoco/jacoco.xml
